# This is a config for E2B sandbox template.
# You can use template ID (izvjugmy05jeo0vwg755) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("izvjugmy05jeo0vwg755") # Sync sandbox
# sandbox = await AsyncSandbox.create("izvjugmy05jeo0vwg755") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('izvjugmy05jeo0vwg755')

team_id = "608eb540-d17b-4420-b632-6514e50a105d"
dockerfile = "e2b.Dockerfile"
template_id = "izvjugmy05jeo0vwg755"
