"""
Code Cache Model
Database model for storing AI-generated code with performance tracking
"""

from sqlalchemy import Column, Integer, String, Text, DateTime, Float, Numeric
from sqlalchemy.sql import func
from datetime import datetime
from . import Base


class CodeCache(Base):
    """
    Code Cache Model

    Stores AI-generated code for reuse across workflow executions.

    Cache Strategy:
        - cache_key = SHA256(prompt + hash(entire context))
        - Reuse code when prompt AND context hash are identical
        - Track usage statistics for performance monitoring

    Example:
        # First execution
        cache_key = "a3f5b9c2d..."
        generated_code = "import fitz\\npdf = ..."
        → Save to cache

        # Second execution (same prompt + context)
        cache_key = "a3f5b9c2d..."  (same hash)
        → Load from cache (no AI call needed)
        → Execute cached code
        → Update usage stats
    """
    __tablename__ = "code_cache"

    # Primary key
    id = Column(Integer, primary_key=True, index=True)

    # Cache identification
    cache_key = Column(
        String(64),
        nullable=False,
        unique=True,
        index=True,
        comment="SHA256 hash of (prompt + context_hash)"
    )

    # Metadata hashes (for analytics)
    task_hash = Column(
        String(64),
        nullable=False,
        index=True,
        comment="Hash of prompt only (for grouping similar tasks)"
    )

    context_schema_hash = Column(
        String(64),
        nullable=True,
        comment="Hash of context schema (structure only)"
    )

    # Cached code
    generated_code = Column(
        Text,
        nullable=False,
        comment="Python code generated by AI"
    )

    # Original generation metadata
    model = Column(
        String(100),
        nullable=False,
        comment="AI model used (e.g., 'gpt-4o-mini')"
    )

    original_prompt = Column(
        Text,
        nullable=True,
        comment="Original prompt/task description"
    )

    tokens_used = Column(
        Integer,
        nullable=True,
        comment="Tokens consumed during code generation"
    )

    cost_usd = Column(
        Numeric(precision=10, scale=6),
        nullable=True,
        comment="Cost in USD for original generation"
    )

    # Usage tracking
    times_reused = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Number of times this code has been reused"
    )

    last_used_at = Column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
        comment="Last time this cache entry was used"
    )

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        comment="When this cache entry was created"
    )

    # Performance tracking
    success_count = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Number of successful executions"
    )

    failure_count = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Number of failed executions"
    )

    avg_execution_time_ms = Column(
        Float,
        nullable=True,
        comment="Average execution time in milliseconds"
    )

    # Optional workflow context (for analytics)
    workflow_id = Column(
        Integer,
        nullable=True,
        comment="Workflow where this code was generated"
    )

    node_id = Column(
        String(255),
        nullable=True,
        comment="Node ID where this code was generated"
    )

    def __repr__(self):
        return (
            f"<CodeCache("
            f"cache_key={self.cache_key[:16]}..., "
            f"times_reused={self.times_reused}, "
            f"success_rate={self.success_rate:.1%}"
            f")>"
        )

    @property
    def success_rate(self) -> float:
        """Calculate success rate (0.0 to 1.0)"""
        total = self.success_count + self.failure_count
        if total == 0:
            return 1.0  # No failures yet, assume success
        return self.success_count / total

    @property
    def is_reliable(self) -> bool:
        """Check if this cache entry is reliable (>80% success rate)"""
        return self.success_rate >= 0.8

    @property
    def total_cost_saved_usd(self) -> float:
        """Calculate total cost saved by reusing this code"""
        if self.cost_usd is None:
            return 0.0
        return float(self.cost_usd) * self.times_reused

    def to_dict(self) -> dict:
        """Convert to dictionary for API responses"""
        return {
            "id": self.id,
            "cache_key": self.cache_key,
            "model": self.model,
            "times_reused": self.times_reused,
            "success_count": self.success_count,
            "failure_count": self.failure_count,
            "success_rate": self.success_rate,
            "cost_usd": float(self.cost_usd) if self.cost_usd else None,
            "total_cost_saved_usd": self.total_cost_saved_usd,
            "avg_execution_time_ms": self.avg_execution_time_ms,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "last_used_at": self.last_used_at.isoformat() if self.last_used_at else None,
            "workflow_id": self.workflow_id,
            "node_id": self.node_id
        }
